name: deploy-auth
on:
  # Merging a PR is regarded as a push, therefore this workflow will run whenever 
  # we merge a PR that contains changes in the auth directory into the main branch
  push:
    branches:
      - main
    paths:
      - 'auth/**'
      
jobs:
  build: # The job id. We'll call it build but could be anything
    runs-on: ubuntu-latest
    steps:
      # checkout the code in our repository (latest branch)
      - uses: actions/checkout@v2
      # Command to run (build the image and push to docker hub)
      - run: cd auth && docker build -t oldledger/auth .
      # Login to docker
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      # Instruct github to add our secrets to this job as environment variables
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      # Push built image to docker hub
      - run: docker push oldledger/auth
      - uses: azure/aks-set-context@v1
        with:
            creds: '${{ secrets.AZURE_CREDENTIALS }}' # Azure credentials
            resource-group: 'ticketingRG'
            cluster-name: 'ticketingCluster'
        id: login
        ### Online template
      - name: Get kubeconfig
        id: kubeconfig
        run: a="$(cat ~/.kube/config)"; a="${a//'%'/'%25'}"; a="${a//$'\n'/'%0A'}"; a="${a//$'\r'/'%0D'}"; echo "::set-output name=config::$a"
      - name: Install Istio
        uses: huang195/actions-install-istio@v1.0.0
        with:
          kubeconfig: "${{steps.kubeconfig.outputs.config}}"
          istio version: '1.6.3'
      - name: Interact with the cluster
        run: kubectl get all --all-namespaces
        ###
      # Instruct github to restart the auth deployment in the cluster
      - run: kubectl rollout restart deployment auth-depl
            
