name: deploy-manifest
on:
  # Merging a PR is regarded as a push, therefore this workflow will run whenever
  # we merge a PR that contains changes in the auth directory into the main branch
  push:
    branches:
      - main
    paths:
      - "infra/**"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Set kubernetes context
      # - uses: azure/k8s-set-context@v1
      #   with:
      #     method: service-account
      #     k8s-url: https://ticketingc-ticketingrg-cec58d-0764636b.hcp.eastus.azmk8s.io:443
      #     k8s-secret: ${{ secrets.K8S_SERVICE_ACCOUNT_SECRETS  }}
      #   id: setcontext
      - uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.K8S_KUBE_CONFIG }}
          context: ticketingCluster-admin
        id: setcontext
      - uses: Azure/k8s-deploy@v1.4
        with:
          manifests: |
            infra/k8s
            infra/k8s-prod
          strategy: canary
          traffic-split-method: smi
          percentage: 20
          baseline-and-canary-replicas: 1
        ###
