name: deploy-manifest
on:
  # Merging a PR is regarded as a push, therefore this workflow will run whenever 
  # we merge a PR that contains changes in the auth directory into the main branch
  push:
    branches:
      - main
    paths:
      - 'infra/**'
      
jobs:
  build: # The job id. We'll call it build but could be anything
    runs-on: ubuntu-latest
    steps:
      # checkout all the code in our repository
      - uses: actions/checkout@v2
      - uses: azure/aks-set-context@v1
        with:
            creds: '${{ secrets.AZURE_CREDENTIALS }}' # Azure credentials
            resource-group: 'ticketingRG'
            cluster-name: 'ticketingCluster'
        id: login
        ### Online template
      - uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: '${{ secrets.AZURE_KUBECONFIG }}'
          context: 'ticketingCluster-admin'
        id: setcontext
        ###
      # Apply all the config files in the k8s directory
      - run: kubectl apply -f infra/k8s -f infra/k8s-prod
            
