name: tests-payments

on:
  pull_request:
    paths: # Only run jobs if there are changes to the files below
      - "payments/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd payments && npm install && npm run test:ci
